from datetime import date
from pathlib import Path

import requests

from constants import DOWNLOAD_DIR, EXCEL_DIR, HEADERS
from services.excel_service import append_extracted_rows, create_workbook, write_headers
from services.path_service import get_site_name
from services.sitemap_extractor_agent_service import (
    ExtractorContractError,
    _read_cached_source,
    _read_meta_header,
    run_extractor_with_timeout,
    safe_exec,
)
from services.sitemap_service import (
    build_sitemap_url,
    create_sitemap_audit,
    finalize_sitemap_audit,
    keep_url,
    read_xml_root_from_file,
    walk_sitemap,
    write_sitemap_audit,
)
from state import PipelineState


# ---------------------------
# Node 1: Download top sitemap XML
# ---------------------------
def download_xml(state: PipelineState) -> dict:
    """Download top sitemap.xml and save it locally."""
    DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)

    base_url = state["base_url"]
    sitemap_url = build_sitemap_url(base_url)

    site_name = get_site_name(base_url)
    file_path = DOWNLOAD_DIR / f"{site_name}.xml"

    response = requests.get(sitemap_url, headers=HEADERS, timeout=30)

    if response.status_code == 403:
        server_name = response.headers.get("server", "unknown")
        raise requests.HTTPError(
            "403 Forbidden while downloading sitemap. "
            f"The site blocked this machine at {sitemap_url} "
            f"(server: {server_name}). "
            "This is typically an anti-bot or IP-level block, not a sitemap path issue.",
            response=response,
        )

    response.raise_for_status()

    file_path.write_bytes(response.content)

    return {"xml_file_path": str(file_path.resolve())}


# ---------------------------
# Helpers shared by extract_urls_to_excel
# ---------------------------
def _build_fetch_xml(session: requests.Session, audit: dict):
    """Return a fetch_xml(url) -> bytes helper for use by generated extractors.

    Handles gzip transparently so generated code does not need to decompress.
    Increments audit['fetch_count'] on each call.
    """

    def fetch_xml(url: str) -> bytes:
        audit["fetch_count"] = audit.get("fetch_count", 0) + 1
        response = session.get(url, headers=HEADERS, timeout=30)
        response.raise_for_status()
        content = response.content
        is_gzip = url.lower().endswith(".gz") or content[:2] == b"\x1f\x8b"
        if is_gzip:
            import gzip as _gzip

            content = _gzip.decompress(content)
        return content

    return fetch_xml


def _try_run_generated_extractor(
    state: PipelineState,
    session: requests.Session,
    cutoff: date,
    audit: dict,
) -> list[dict] | None:
    """Run the cached/generated extractor. Return rows or None on any failure."""
    script_path = state.get("extractor_script_path", "") or ""
    if not script_path:
        return None

    cache_file = Path(script_path)
    if not cache_file.exists():
        audit["extractor_failure_reason"] = "cache file missing"
        return None

    try:
        meta = _read_meta_header(cache_file)
        audit["extractor_sample_hash"] = meta.get("sample_hash", "")
        audit["extractor_generation_model"] = meta.get("model", "")

        source = _read_cached_source(cache_file)
        extractor_fn = safe_exec(source)
        fetch_xml = _build_fetch_xml(session, audit)
        rows, runtime = run_extractor_with_timeout(extractor_fn, state["xml_file_path"], cutoff, fetch_xml)
        audit["extractor_runtime_ms"] = int(runtime * 1000)
        return rows
    except ExtractorContractError as exc:
        audit["extractor_failure_reason"] = f"contract: {exc}"
        return None
    except Exception as exc:  # noqa: BLE001 - extractor is external code
        audit["extractor_failure_reason"] = f"runtime: {exc}"
        return None


def _dedupe_rows(rows: list[dict]) -> list[dict]:
    seen: set[str] = set()
    unique: list[dict] = []
    for row in rows:
        link = row.get("link", "")
        if link and link not in seen:
            seen.add(link)
            unique.append({"link": link, "lastmod": row.get("lastmod", "")})
    return unique


# ---------------------------
# Node 2: Extract URLs and save them to Excel
# ---------------------------
def extract_urls_to_excel(state: PipelineState) -> dict:
    """Extract final article URLs and save them to an Excel file.

    Strategy:
    1. Try the per-site extractor generated by `generate_sitemap_extractor`.
    2. If unavailable, fails, or post-filter rejects more than half its rows,
       fall back to the generic recursive walker in services/sitemap_service.

    The Excel file starts with these columns:
    - link
    - lastmod
    - markdown_path
    - markdown_status
    """
    cutoff = date.fromisoformat(state["cutoff_date"])
    site_name = get_site_name(state["base_url"])

    audit = create_sitemap_audit(
        site_name=site_name,
        cutoff=cutoff,
        top_sitemap_path=state["xml_file_path"],
    )
    audit["extractor_source"] = state.get("extractor_source", "fallback")
    audit["extractor_sample_hash"] = ""
    audit["extractor_generation_model"] = ""
    audit["extractor_runtime_ms"] = 0
    audit["fetch_count"] = 0
    audit["extractor_failure_reason"] = ""

    final_rows: list[dict] = []

    with requests.Session() as session:
        session.headers.update(HEADERS)

        used_generated = False
        generated_rows = _try_run_generated_extractor(state, session, cutoff, audit)

        if generated_rows is not None:
            unique = _dedupe_rows(generated_rows)
            audit["final_urls_seen"] = len(unique)
            kept = [row for row in unique if keep_url(str(row.get("lastmod", "")), cutoff)]
            kept_ratio = (len(kept) / len(unique)) if unique else 0.0

            sanity_pass = len(unique) > 0 and (kept_ratio >= 0.5 or len(kept) >= 25)
            if sanity_pass:
                final_rows = kept
                used_generated = True
                audit["final_urls_skipped_before_cutoff"] = len(unique) - len(kept)
            else:
                audit["extractor_failure_reason"] = (
                    f"sanity check failed: {len(kept)}/{len(unique)} rows passed cutoff"
                )

        if not used_generated:
            audit["extractor_source"] = "fallback"
            top_root = read_xml_root_from_file(state["xml_file_path"])
            walk_rows: list[dict] = []
            seen_sitemaps: set[str] = set()
            seen_links: set[str] = set()

            walker_audit = create_sitemap_audit(
                site_name=site_name,
                cutoff=cutoff,
                top_sitemap_path=state["xml_file_path"],
            )
            walk_sitemap(
                root=top_root,
                session=session,
                cutoff=cutoff,
                final_rows=walk_rows,
                seen_sitemaps=seen_sitemaps,
                seen_links=seen_links,
                audit=walker_audit,
            )

            filtered_rows: list[dict] = []
            for row in walk_rows:
                if keep_url(str(row.get("lastmod", "")), cutoff):
                    filtered_rows.append(row)
                    continue
                walker_audit["guard_rows_removed_after_walk"] += 1
                samples = walker_audit.setdefault("guard_rows_removed_samples", [])
                if len(samples) < 10:
                    samples.append(
                        {
                            "link": row.get("link", ""),
                            "lastmod": row.get("lastmod", ""),
                        }
                    )

            final_rows = filtered_rows
            # Merge walker stats into the main audit so the JSON keeps the same shape.
            for key in (
                "sitemapindex_nodes_traversed",
                "urlset_nodes_traversed",
                "child_sitemaps_seen",
                "child_sitemaps_opened",
                "child_sitemaps_skipped_before_cutoff",
                "child_sitemap_samples_opened_recent_lastmod",
                "child_sitemap_samples_skipped_before_cutoff",
                "final_urls_seen",
                "final_urls_skipped_before_cutoff",
                "final_url_samples_skipped_before_cutoff",
                "guard_rows_removed_after_walk",
                "guard_rows_removed_samples",
            ):
                audit[key] = walker_audit[key]

    finalize_sitemap_audit(audit, final_rows)
    audit_file_path = write_sitemap_audit(site_name, audit)

    print(
        f"{site_name}: kept {audit['final_urls_kept']} URLs "
        f"(extractor={audit['extractor_source']}, fetches={audit['fetch_count']}), "
        f"kept range {audit['kept_min_lastmod'] or 'n/a'}..{audit['kept_max_lastmod'] or 'n/a'}"
    )

    # Create site-specific Excel folder and file.
    site_excel_dir = EXCEL_DIR / site_name
    site_excel_dir.mkdir(parents=True, exist_ok=True)
    excel_path = site_excel_dir / f"{site_name}_urls.xlsx"

    workbook = create_workbook()
    worksheet = workbook.active
    worksheet.title = site_name[:31]

    # Write header row.
    write_headers(worksheet)

    # Write extracted sitemap rows.
    append_extracted_rows(worksheet, final_rows)

    workbook.save(excel_path)
    workbook.close()

    return {
        "excel_file_path": str(excel_path.resolve()),
        "sitemap_audit_file_path": audit_file_path,
    }
